language: php
php:
  - 7.3
  - 7.4
before_install:
  - curl -s https://get.sdkman.io | bash
  - source "/home/travis/.sdkman/bin/sdkman-init.sh"
  - sdk install kotlin
  - composer install
script:
  - composer run tests
